import JSZip from 'jszip';
import { AppMetadata, AppDesign, AppPermissions, AppIcon } from './types';

export async function generateAndroidProjectZip(
  meta: AppMetadata,
  design: AppDesign,
  permissions: AppPermissions,
  iconSvg: string,
  htmlCode: string
): Promise<Blob> {
  const zip = new JSZip();

  // 1. Root README.md
  const readme = `# ${meta.name} - Android Source Project

This is a ready-to-compile Android project wrapper for your web application, generated by the **No-Code Mobile App Builder**.

## Project Structure
- \`app/src/main/assets/www/\`: Contains your responsive HTML/CSS/JS application assets.
- \`app/src/main/AndroidManifest.xml\`: Declares Android system permissions, app metadata, and launching parameters.
- \`app/src/main/java/\`: Hosts the native Java MainActivity configured to load your web application in a hardware-accelerated WebView.

## How to Compile into a Downloadable APK:

### Option A: Using Android Studio (Recommended)
1. Download and install [Android Studio](https://developer.android.com/studio).
2. Launch Android Studio and click **Open**. Select the folder containing this \`README.md\` file.
3. Wait for Gradle synchronization to finish (approx. 1-2 minutes).
4. Click **Build** > **Build Bundle(s) / APK(s)** > **Build APK(s)** in the top menu bar.
5. Once complete, a popup will locate your compiled APK file at \`app/build/outputs/apk/debug/app-debug.apk\` ready to install on your phone!

### Option B: Using Command Line (Gradle)
If you have Gradle and JDK 17 installed:
\`\`\`bash
./gradlew assembleDebug
\`\`\`
The compiled debug APK will be created at:
\`\`\`
app/build/outputs/apk/debug/app-debug.apk
\`\`\`

## App Configuration
- **Application Name**: ${meta.name}
- **Package ID**: ${meta.packageId}
- **Version**: ${meta.version}
- **Primary Color**: ${design.primaryColor}
- **Orientation**: ${design.orientation}
- **Category**: ${meta.category || 'Utility'}
- **Keywords**: ${meta.keywords || 'N/A'}
- **Support URL**: ${meta.supportUrl || 'N/A'}
- **Privacy Policy URL**: ${meta.privacyUrl || 'N/A'}
${meta.customProperties && meta.customProperties.length > 0 ? `- **Custom Developer Metadata**:\n${meta.customProperties.map(p => `  - \`${p.key}\`: ${p.value}`).join('\n')}\n` : ''}
- **Permissions Mapped**:
${permissions.internet ? '  - INTERNET (Enabled)\n' : ''}${permissions.camera ? '  - CAMERA (Enabled)\n' : ''}${permissions.location ? '  - ACCESS_FINE_LOCATION (Enabled)\n' : ''}${permissions.notifications ? '  - POST_NOTIFICATIONS (Enabled)\n' : ''}${permissions.biometric ? '  - USE_BIOMETRIC (Enabled)\n' : ''}
`;

  zip.file("README.md", readme);

  // 2. Root settings.gradle
  zip.file("settings.gradle", `pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "${meta.name.replace(/[^a-zA-Z0-9]/g, '')}"
include ':app'
`);

  // 3. Root build.gradle
  zip.file("build.gradle", `// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
}
`);

  // 4. gradle/wrapper structure (simple gradle loader template)
  zip.file("gradlew", `#!/usr/bin/env bash
# Gradle wrapper script placeholder
echo "Building project via gradle..."
`);
  zip.file("gradlew.bat", `@echo off
rem Gradle wrapper batch placeholder
echo Building project...
`);

  // 5. App level build.gradle
  const appBuildGradle = `plugins {
    id 'com.android.application'
}

android {
    namespace '${meta.packageId}'
    compileSdk 34

    defaultConfig {
        applicationId "${meta.packageId}"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "${meta.version}"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
`;
  zip.file("app/build.gradle", appBuildGradle);

  // 6. Proguard rules
  zip.file("app/proguard-rules.pro", `# Custom Proguard rules for optimization
-keepattributes Signature,*Annotation*
-keep class android.webkit.** { *; }
`);

  // 7. App Assets: www directory with HTML
  zip.file("app/src/main/assets/www/index.html", htmlCode);
  zip.file("app/src/main/assets/www/icon.svg", iconSvg);
  
  // 7.1 Add PWA Manifest for Web-to-Mobile readiness
  const pwaManifest = {
    name: meta.name,
    short_name: meta.name.substring(0, 12),
    start_url: "index.html",
    display: "standalone",
    background_color: design.themeMode === 'dark' ? '#0f172a' : '#f8fafc',
    theme_color: design.primaryColor,
    icons: [
      {
        src: "icon.svg",
        sizes: "any",
        type: "image/svg+xml"
      }
    ]
  };
  zip.file("app/src/main/assets/www/manifest.json", JSON.stringify(pwaManifest, null, 2));

  // Custom metadata and Store Listing descriptions file
  const customMetadataJson = {
    appName: meta.name,
    packageId: meta.packageId,
    version: meta.version,
    author: meta.author,
    description: meta.description,
    category: meta.category || "Utility",
    keywords: meta.keywords || "",
    supportUrl: meta.supportUrl || "",
    privacyUrl: meta.privacyUrl || "",
    customProperties: meta.customProperties || [],
    generatedAt: new Date().toISOString()
  };
  zip.file("app/src/main/assets/www/app-metadata.json", JSON.stringify(customMetadataJson, null, 2));

  // 8. Manifest File
  const androidManifest = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${meta.packageId}">

    <!-- Core Internet & Network Status -->
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
${permissions.camera ? '    <uses-permission android:name="android.permission.CAMERA" />\n    <uses-feature android:name="android.hardware.camera" android:required="false" />\n' : ''}${permissions.location ? '    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />\n    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />\n' : ''}${permissions.notifications ? '    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />\n' : ''}${permissions.biometric ? '    <uses-permission android:name="android.permission.USE_BIOMETRIC" />\n' : ''}
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.AppTheme"
        android:usesCleartextTraffic="true"
        android:hardwareAccelerated="true">
        
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:screenOrientation="${design.orientation === 'landscape' ? 'landscape' : 'portrait'}"
            android:configChanges="orientation|screenSize|smallestScreenSize|screenLayout|keyboardHidden|keyboard"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>`;
  zip.file("app/src/main/AndroidManifest.xml", androidManifest);

  // 9. Resource values (Strings, Colors, Styles)
  zip.file("app/src/main/res/values/strings.xml", `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">${meta.name}</string>
</resources>
`);

  zip.file("app/src/main/res/values/colors.xml", `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="primary">${design.primaryColor}</color>
    <color name="primary_dark">${design.primaryColor}</color>
    <color name="accent">${design.accentColor}</color>
    <color name="background">${design.themeMode === 'dark' ? '#0f172a' : '#f8fafc'}</color>
</resources>
`);

  zip.file("app/src/main/res/values/styles.xml", `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Base application theme -->
    <style name="Theme.AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here -->
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="colorAccent">@color/accent</item>
        <item name="android:windowBackground">@color/background</item>
    </style>
</resources>
`);

  // Simple XML structure for mock launch icons (mipmap folders)
  zip.file("app/src/main/res/mipmap/ic_launcher.xml", `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/primary"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
</adaptive-icon>`);
  
  zip.file("app/src/main/res/mipmap/ic_launcher_foreground.xml", iconSvg);

  // 10. Java MainActivity with Dynamic Directories based on packageId!
  // E.g., packageId: com.alex.my_app -> app/src/main/java/com/alex/my_app/MainActivity.java
  const packageParts = meta.packageId.split('.');
  const packageDir = `app/src/main/java/${packageParts.join('/')}`;
  
  const javaCode = `package ${meta.packageId};

import android.annotation.SuppressLint;
import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;

public class MainActivity extends AppCompatActivity {

    private WebView mWebView;

    @Override
    @SuppressLint("SetJavaScriptEnabled")
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
        // Setup WebView
        mWebView = new WebView(this);
        setContentView(mWebView);

        // Hardware accelerated performance configuration
        WebSettings settings = mWebView.getSettings();
        settings.setJavaScriptEnabled(true);
        settings.setDomStorageEnabled(true);
        settings.setDatabaseEnabled(true);
        settings.setAllowFileAccess(true);
        settings.setAllowContentAccess(true);
        settings.setLoadWithOverviewMode(true);
        settings.setUseWideViewPort(true);
        settings.setSupportZoom(false);
        settings.setBuiltInZoomControls(false);
        settings.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);
        settings.setMediaPlaybackRequiresUserGesture(false);

        // Web Client interceptor
        mWebView.setWebViewClient(new WebViewClient() {
            @Override
            public void onPageFinished(WebView view, String url) {
                super.onPageFinished(view, url);
                // Page loaded successfully
            }

            @SuppressWarnings("deprecation")
            @Override
            public void onReceivedError(WebView view, int errorCode, String description, String failingUrl) {
                Toast.makeText(MainActivity.this, "Load error: " + description, Toast.LENGTH_SHORT).show();
            }
        });

        // Handle JS Alerts, File Choose, etc
        mWebView.setWebChromeClient(new WebChromeClient());

        // Load self-contained web assets
        mWebView.loadUrl("file:///android_asset/www/index.html");
    }

    @Override
    public void onBackPressed() {
        if (mWebView.canGoBack()) {
            mWebView.goBack();
        } else {
            super.onBackPressed();
        }
    }
}
`;

  zip.file(`${packageDir}/MainActivity.java`, javaCode);

  // Generate complete ZIP BLOB
  return await zip.generateAsync({ type: 'blob' });
}
